# Generated by Django 5.0.1 on 2024-02-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_remove_cart_items_remove_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='ShopApp.product'),
        ),
    ]
